document.addEventListener("DOMContentLoaded",()=>{
const S={name:"",phone:"",guestCount:1,guests:[{label:"Guest 1",services:[],staff:""}],date:"",time:""};let step=0,activeGuest=0;
const titles=[["Step 1 of 5","Who is booking?"],["Step 2 of 5","How many guests?"],["Step 3 of 5","Choose services & staff"],["Step 4 of 5","Select date & time"],["Step 5 of 5","Review your appointment"]];
const morning=["10:00 AM","10:15 AM","10:30 AM","10:45 AM","11:00 AM","11:15 AM","11:30 AM","11:45 AM"],afternoon=["12:00 PM","12:15 PM","12:30 PM","12:45 PM","1:00 PM","1:15 PM","1:30 PM","1:45 PM","2:00 PM","2:15 PM","2:30 PM","2:45 PM","3:00 PM","3:15 PM","3:30 PM","3:45 PM","4:00 PM","4:15 PM","4:30 PM","4:45 PM","5:00 PM","5:15 PM","5:30 PM","5:45 PM","6:00 PM","6:15 PM","6:30 PM"];
const $=id=>document.getElementById(id),esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};$("bookingDate").min=today();
const fmt=v=>v?new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"}).format(new Date(`${v}T12:00:00`)):"Not selected";
function ensure(n){const old=S.guests;S.guests=Array.from({length:n},(_,i)=>old[i]||{label:`Guest ${i+1}`,services:[],staff:""});S.guestCount=n;activeGuest=Math.min(activeGuest,n-1)}
function counts(){const box=$("guestCountGrid");box.innerHTML="";for(let i=1;i<=7;i++){const b=document.createElement("button");b.className=`count ${S.guestCount===i?"selected":""}`;b.innerHTML=`<strong>${i}</strong><span>${i===1?"Guest":"Guests"}</span>`;b.onclick=()=>{ensure(i);counts();editor();valid()};box.appendChild(b)}}
function editor(){const tabs=$("guestTabs");tabs.innerHTML="";S.guests.forEach((g,i)=>{const b=document.createElement("button");b.className=i===activeGuest?"active":"";b.textContent=`Guest ${i+1}${g.services.length?` (${g.services.length})`:""}`;b.onclick=()=>{activeGuest=i;editor()};tabs.appendChild(b)});const g=S.guests[activeGuest];$("guestEditor").innerHTML=`<div class="guest-top"><label><span>Guest Display Name</span><input id="guestLabel" maxlength="50" value="${esc(g.label)}"></label><div><span>Selected services</span><strong>${g.services.length}</strong></div></div><section class="edit-block"><h4>Preferred Staff *</h4><div id="staffGrid" class="staff-grid"></div></section><section class="edit-block"><div class="service-head"><h4>Services * <small>Select as many as needed</small></h4><input id="serviceSearch" placeholder="Search services..."></div><div id="serviceMenu"></div></section>`;$("guestLabel").oninput=e=>g.label=e.target.value||`Guest ${activeGuest+1}`;staff(g);services(g);$("serviceSearch").oninput=e=>services(g,e.target.value)}
function staff(g){const box=$("staffGrid");window.HERMOSA_STAFF.forEach(s=>{const b=document.createElement("button");b.className=`staff ${g.staff===s.name?"selected":""}`;b.innerHTML=`<strong>${s.name}</strong><small>${s.description}</small><i>✓</i>`;b.onclick=()=>{g.staff=s.name;editor();valid()};box.appendChild(b)})}
function services(g,q=""){const box=$("serviceMenu");box.innerHTML="";q=q.toLowerCase().trim();Object.entries(window.HERMOSA_MENU).forEach(([cat,items])=>{items=items.filter(x=>x.name.toLowerCase().includes(q));if(!items.length)return;const group=document.createElement("div");group.className="service-group open";group.innerHTML=`<button class="group-head"><strong>${cat}</strong><span>⌄</span></button><div class="service-list"></div>`;group.querySelector(".group-head").onclick=()=>group.classList.toggle("open");const list=group.querySelector(".service-list");items.forEach(item=>{const on=g.services.some(x=>x.name===item.name),b=document.createElement("button");b.className=`service ${on?"selected":""}`;b.innerHTML=`<span><b>${item.name}</b><small>${cat}</small></span><strong>${item.price}</strong><i>${on?"✓":"+"}</i>`;b.onclick=()=>{const i=g.services.findIndex(x=>x.name===item.name);i>=0?g.services.splice(i,1):g.services.push({...item});editor();valid()};list.appendChild(b)});box.appendChild(group)})}
function times(id,arr){const box=$(id);box.innerHTML="";arr.forEach(t=>{const b=document.createElement("button");b.className=`time ${S.time===t?"selected":""}`;b.textContent=t;b.disabled=!S.date;b.onclick=()=>{S.time=t;allTimes();schedule();valid()};box.appendChild(b)})}function allTimes(){times("morningSlots",morning);times("afternoonSlots",afternoon)}function schedule(){$("chosenSchedule").textContent=S.date&&S.time?`${fmt(S.date)} at ${S.time}`:"Select a date and time"}
function ok(i=step){if(i===0)return S.name.trim().length>=2&&S.phone.replace(/\D/g,"").length>=7;if(i===1)return S.guestCount>0;if(i===2)return S.guests.every(g=>g.staff&&g.services.length);if(i===3)return S.date>=today()&&!!S.time;return true}
function valid(){const hints=[ok()?"Contact information complete.":"Enter your name and phone number.",`${S.guestCount} guest${S.guestCount>1?"s":""} selected.`,ok()?"Every guest is ready.":"Each guest needs staff and at least one service.",ok()?"Schedule selected.":"Select a valid date and time.","Review before confirming."];$("nextBtn").disabled=!ok();$("footerHint").textContent=hints[step]}
function go(n){for(let i=0;i<n;i++)if(!ok(i))return;step=n;document.querySelectorAll(".step").forEach((x,i)=>x.classList.toggle("active",i===n));document.querySelectorAll(".side").forEach((x,i)=>x.classList.toggle("active",i===n));$("stepLabel").textContent=titles[n][0];$("stepTitle").textContent=titles[n][1];$("progressFill").style.width=`${(n+1)*20}%`;$("backBtn").disabled=n===0;$("nextBtn").style.display=n===4?"none":"";if(n===2)editor();if(n===4)review();valid();document.querySelector(".panel").scrollIntoView({behavior:"smooth",block:"start"})}
function review(){$("reviewContact").innerHTML=`<div><span>Booking Name</span><strong>${esc(S.name)}</strong></div><div><span>Phone</span><strong>${esc(S.phone)}</strong></div><div><span>Date</span><strong>${fmt(S.date)}</strong></div><div><span>Time</span><strong>${S.time}</strong></div>`;$("reviewGuests").innerHTML=S.guests.map((g,i)=>`<article><header><span>Guest ${i+1}</span><strong>${esc(g.label)}</strong></header><p><b>Staff:</b> ${esc(g.staff)}</p><ul>${g.services.map(s=>`<li><span>${esc(s.name)}</span><strong>${esc(s.price)}</strong></li>`).join("")}</ul></article>`).join("")}
$("customerName").oninput=e=>{S.name=e.target.value;valid()};$("customerPhone").oninput=e=>{S.phone=e.target.value;valid()};$("bookingDate").onchange=e=>{S.date=e.target.value>=today()?e.target.value:"";S.time="";e.target.value=S.date;allTimes();schedule();valid()};$("backBtn").onclick=()=>go(step-1);$("nextBtn").onclick=()=>go(step+1);document.querySelectorAll("[data-jump]").forEach(b=>b.onclick=()=>go(+b.dataset.jump));
$("confirmBooking").onclick=async e=>{const b=e.currentTarget;b.disabled=true;b.textContent="Submitting...";try{const r=await fetch("/api/bookings/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(S)}),d=await r.json();if(!r.ok)throw Error(d.error||"Booking failed");$("bookingCode").textContent=d.code;$("successModal").classList.add("show");document.body.style.overflow="hidden"}catch(err){alert(err.message)}finally{b.disabled=false;b.textContent="Confirm Appointment →"}};$("copyCode").onclick=async()=>{await navigator.clipboard.writeText($("bookingCode").textContent);$("copyCode").textContent="Copied!"};ensure(1);counts();editor();allTimes();go(0)
});
